### PR TITLE
Add arm build

### PR DESCRIPTION
**Pull request by a-thomas-22**

### CODE REVIEW

**Comment by thedatabaseme** [comment]
@a-thomas-22 Thanks for contributing. Some more information would be nice. 

- You decided to use a separate `downloader`. Why not include the if section with `TARGETARCH` into the `#Build final image` part?
- Also, I'm not sure where the `TARGETARCH` argument is set during build in the Github action. 

In general, it's hard to test for me, since I don't have an ARM platform client at hand. I will try to get something setup to test your PR.

Kind regards
Philip

**Comment by thedatabaseme** [comment]
@a-thomas-22 Ok. I've tested it. Works also for me. Still, I would like to discuss, if it's not more reasonable to fetch the wal-g binary within the build step instead of having it in the `download` artifact.

**Comment by a-thomas-22** [comment]
Sorry, probably should have put a comment on this one. 

I have this running and building a slightly modified build workflow(only change is it pushes the docker image somewhere else) which we use to run the wal-g-exporter on our arm systems. The spilo image and the postgres exporter already run on arm, so this is the last piece that allows our kubernetes zalando postgres pods to schedule on arm nodes.

As far as the downloader stage, that is more just a personal preference. Keeps things a bit more modular and easy to debug if needed.  In a simple dockerfile it doesn't matter much either way.

Putting them in the same stage would look like this I think (untested). Let me know if you would prefer it that way and I will test it and make the change.

```# Build exporter and download wal-g
FROM python:3.9.16-bullseye AS exporter-builder

WORKDIR /usr/src/

# Install exporter requirements and build
COPY requirements.txt /usr/src/
RUN pip3 install -r requirements.txt
ADD exporter.py /usr/src/
RUN pyinstaller --name exporter \
    --onefile exporter.py && \
    mv dist/exporter wal-g-prometheus-exporter

# Install wget and download wal-g
ARG TARGETARCH
RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/* && \
    if [ "${TARGETARCH}" = "arm64" ]; then \
        export WALG_ARCH="aarch64"; \
    else \
        export WALG_ARCH="${TARGETARCH}"; \
    fi && \
    wget -O /wal-g-pg-ubuntu-20.04.tar.gz https://github.com/wal-g/wal-g/releases/download/v2.0.1/wal-g-pg-ubuntu-20.04-${WALG_ARCH}.tar.gz

# Build final image
FROM debian:11.6-slim
COPY --from=exporter-builder /usr/src/wal-g-prometheus-exporter /usr/bin/
COPY --from=exporter-builder /wal-g-pg-ubuntu-20.04.tar.gz /usr/bin/

RUN apt-get update && \
    apt-get install -y ca-certificates daemontools && \
    apt-get upgrade -y -q && \
    apt-get dist-upgrade -y -q && \
    apt-get -y -q autoclean && \
    apt-get -y -q autoremove

RUN cd /usr/bin/ && \
    tar -zxvf wal-g-pg-ubuntu-20.04.tar.gz && \
    rm wal-g-pg-ubuntu-20.04.tar.gz && \
    (mv wal-g-pg-ubuntu20.04-* wal-g || mv wal-g-pg-ubuntu-20.04-* wal-g)

COPY scripts/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["/usr/bin/entry
```

**Comment by thedatabaseme** [comment]
I will test the build with the above mentioned changes and provide feedback.

**Comment by a-thomas-22** [comment]
Made the change and tested it on my end.

**Comment by thedatabaseme** [comment]
@a-thomas-22  Merged. Thanks again for contributing.

**Pull request merged**
